# Generated by Django 5.0.2 on 2024-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empnm', models.CharField(max_length=35)),
                ('empadd', models.CharField(max_length=35)),
                ('empsal', models.FloatField()),
            ],
        ),
    ]
